"""Add ordered immutable event fields required by MemoryService.write.

Revision ID: 20260731_0002
Revises: 20260731_0001
Create Date: 2026-07-31
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260731_0002"
down_revision: str | None = "20260731_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # IF NOT EXISTS keeps the migration compatible with fresh databases while
    # the initial metadata-backed baseline remains frozen at its applied state.
    op.execute(
        "ALTER TABLE memory_events ADD COLUMN IF NOT EXISTS "
        "event_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "ALTER TABLE memory_events ADD COLUMN IF NOT EXISTS "
        "role VARCHAR(64) NOT NULL DEFAULT 'unknown'"
    )
    op.execute(
        "ALTER TABLE memory_events ADD COLUMN IF NOT EXISTS "
        "source VARCHAR(256) NOT NULL DEFAULT 'unknown'"
    )
    for column_name in ("file_refs", "tool_result_refs", "artifact_refs"):
        op.execute(
            f"ALTER TABLE memory_events ADD COLUMN IF NOT EXISTS {column_name} "
            "JSONB NOT NULL DEFAULT '[]'::jsonb"
        )
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'uq_memory_events_tenant_sequence'
          ) THEN
            ALTER TABLE memory_events
            ADD CONSTRAINT uq_memory_events_tenant_sequence
            UNIQUE (tenant_id, event_sequence);
          END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE memory_events "
        "DROP CONSTRAINT IF EXISTS uq_memory_events_tenant_sequence"
    )
    for column_name in (
        "artifact_refs",
        "tool_result_refs",
        "file_refs",
        "source",
        "role",
        "event_sequence",
    ):
        op.execute(f"ALTER TABLE memory_events DROP COLUMN IF EXISTS {column_name}")
